---
# tasks file for docker
- apt: name=lxc-docker state=absent purge=yes
  become: yes

- apt: upgrade=dist
  become: yes

- apt: name={{ item }} update_cache=yes cache_valid_time=300
  become: yes
  with_items:
    - apt-transport-https
    - ca-certificates

- apt_key: keyserver="hkp://p80.pool.sks-keyservers.net:80" id=58118E89F3A912897C070ADBF76221572C52609D
  become: yes

- apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
  become: yes

- apt: name=linux-image-extra-{{ ansible_kernel }} update_cache=yes cache_valid_time=300
  become: yes

- apt: name=docker-engine update_cache=yes cache_valid_time=300
  become: yes

# - service: name=docker enabled=yes state=started
#   become: yes

- get_url: url="https://github.com/docker/compose/releases/download/{{ DCKR_COMPOSE_VERSION }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}" dest=/usr/local/bin/docker-compose mode=0755
  become: yes

- command: /usr/local/bin/docker-compose --version
  become: yes
